package Views;
import Models.Clientes;
import Models.Inventario;
import Models.Ventas;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author damon
 */
public class Sistema extends javax.swing.JFrame {
    Clientes cl = new Clientes() ;
    Clientes.Cliente cliente = null;
    Inventario proD = new Inventario();
    double totalPagar = 0.00;
    DefaultTableModel modeloHistorialVentas;
    Ventas ventas = new Ventas();

    //Constructor
    public Sistema() {
        initComponents();
        setLocationRelativeTo(null);
        inicializarTabla(); 
        inicializarTablaHistorial();
        modeloHistorialVentas = (DefaultTableModel) tablaVentas.getModel();
        tab3.setBorder(BorderFactory.createEmptyBorder());
        tab3.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
    @Override
    protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
        return 0;
    }
    @Override
    protected void paintContentBorder(java.awt.Graphics g, int tabPlacement, int selectedIndex) {
        // No dibuja ningún borde
    }
    });
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        tab3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtStockVenta = new javax.swing.JTextField();
        txtCodigoVenta = new javax.swing.JTextField();
        txtDescripcionVenta = new javax.swing.JTextField();
        txtCantidadVenta = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        btnEliminarVenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVenta = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtIdVenta = new javax.swing.JTextField();
        txtTelefonoVenta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNombreVenta = new javax.swing.JTextField();
        LabelTotal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        btnNuevoCliente = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPrecioInventario = new javax.swing.JTextField();
        txtCodigoInventario = new javax.swing.JTextField();
        txtNombreInventario = new javax.swing.JTextField();
        txtStockInventario = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        btnNuevoInventario = new javax.swing.JButton();
        btnGuardarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(237, 237, 237));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 8, -1, -1));
        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 8, -1, -1));
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 8, -1, -1));
        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 8, -1, -1));

        jLabel8.setText("Stock");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel9.setText("Codigo");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel10.setText("Descripcion");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel11.setText("Cantidad");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel12.setText("Precio");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 70, 30));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 30));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 170, 30));

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 90, 30));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 70, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(221, 255, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Íconos de salud y farmacia.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 150, 110));

        btnSalir.setBackground(new java.awt.Color(178, 255, 215));
        btnSalir.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 120, 30));

        btnInicio.setBackground(new java.awt.Color(178, 255, 215));
        btnInicio.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, 30));

        btnVentas.setBackground(new java.awt.Color(178, 255, 215));
        btnVentas.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/presentation-analytics.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 120, -1));

        btnInventario.setBackground(new java.awt.Color(178, 255, 215));
        btnInventario.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(0, 0, 0));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/indent-increase.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, 30));

        btnClientes.setBackground(new java.awt.Color(178, 255, 215));
        btnClientes.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 120, 30));

        jButton1.setBackground(new java.awt.Color(175, 255, 215));
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 500));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 550, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Stock");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Codigo");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Descripcion");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Cantidad");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Precio");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        txtStockVenta.setEditable(false);
        txtStockVenta.setBackground(new java.awt.Color(153, 255, 204));
        jPanel8.add(txtStockVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 80, -1));

        txtCodigoVenta.setBackground(new java.awt.Color(153, 255, 204));
        txtCodigoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoVentaActionPerformed(evt);
            }
        });
        txtCodigoVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoVentaKeyPressed(evt);
            }
        });
        jPanel8.add(txtCodigoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, -1));

        txtDescripcionVenta.setBackground(new java.awt.Color(153, 255, 204));
        jPanel8.add(txtDescripcionVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, -1));

        txtCantidadVenta.setBackground(new java.awt.Color(153, 255, 204));
        txtCantidadVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadVentaActionPerformed(evt);
            }
        });
        txtCantidadVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadVentaKeyPressed(evt);
            }
        });
        jPanel8.add(txtCantidadVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 60, -1));

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.setBackground(new java.awt.Color(153, 255, 204));
        jPanel8.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 70, -1));

        btnEliminarVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarVenta.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        btnEliminarVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ELIMINAR.png"))); // NOI18N
        btnEliminarVenta.setText("Eliminar");
        btnEliminarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVentaActionPerformed(evt);
            }
        });
        jPanel8.add(btnEliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 30));

        tableVenta.setBackground(new java.awt.Color(255, 255, 255));
        tableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Stock"
            }
        ));
        tableVenta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableVenta);
        if (tableVenta.getColumnModel().getColumnCount() > 0) {
            tableVenta.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableVenta.getColumnModel().getColumn(1).setPreferredWidth(50);
            tableVenta.getColumnModel().getColumn(2).setPreferredWidth(40);
            tableVenta.getColumnModel().getColumn(3).setPreferredWidth(40);
            tableVenta.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 140));

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Total a pagar");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        txtIdVenta.setBackground(new java.awt.Color(153, 255, 204));
        txtIdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVentaActionPerformed(evt);
            }
        });
        jPanel8.add(txtIdVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, -1));

        txtTelefonoVenta.setEditable(false);
        txtTelefonoVenta.setBackground(new java.awt.Color(153, 255, 204));
        txtTelefonoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoVentaActionPerformed(evt);
            }
        });
        jPanel8.add(txtTelefonoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 20, 20));

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("ID");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nombre");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        txtNombreVenta.setEditable(false);
        txtNombreVenta.setBackground(new java.awt.Color(153, 255, 204));
        txtNombreVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreVentaActionPerformed(evt);
            }
        });
        jPanel8.add(txtNombreVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 140, -1));

        LabelTotal.setForeground(new java.awt.Color(0, 0, 0));
        LabelTotal.setText("---");
        jPanel8.add(LabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMPRIMIR.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 50, 40));

        tab3.addTab("tab1", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("TELEFONO");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("ID");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel24.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("NOMBRE");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txtTelefonoCliente.setBackground(new java.awt.Color(153, 255, 204));
        jPanel9.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, -1));

        txtIdCliente.setBackground(new java.awt.Color(153, 255, 204));
        jPanel9.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, -1));

        txtNombreCliente.setBackground(new java.awt.Color(153, 255, 204));
        jPanel9.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));

        tablaCliente.setBackground(new java.awt.Color(255, 255, 255));
        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "TELEFONO"
            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCliente);
        if (tablaCliente.getColumnModel().getColumnCount() > 0) {
            tablaCliente.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaCliente.getColumnModel().getColumn(1).setPreferredWidth(40);
            tablaCliente.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 370, 190));

        btnNuevoCliente.setBackground(new java.awt.Color(178, 255, 216));
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NUEVO.png"))); // NOI18N
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        jPanel9.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 50, 50));

        btnAgregarCliente.setBackground(new java.awt.Color(178, 255, 216));
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AGREGAR.png"))); // NOI18N
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel9.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 50, 50));

        btnEliminarCliente.setBackground(new java.awt.Color(178, 255, 216));
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ELIMINAR.png"))); // NOI18N
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel9.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 190, 50, 50));

        btnActualizarCliente.setBackground(new java.awt.Color(178, 255, 216));
        btnActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ACTUALIZAR.png"))); // NOI18N
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });
        jPanel9.add(btnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 50));

        tab3.addTab("tab2", jPanel9);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaVentas.setBackground(new java.awt.Color(255, 255, 255));
        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CLIENTE", "VENDEDOR", "TOTAL"
            }
        ));
        jScrollPane4.setViewportView(tablaVentas);
        if (tablaVentas.getColumnModel().getColumnCount() > 0) {
            tablaVentas.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaVentas.getColumnModel().getColumn(1).setPreferredWidth(50);
            tablaVentas.getColumnModel().getColumn(2).setPreferredWidth(50);
            tablaVentas.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel11.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 510, 200));

        tab3.addTab("tab3", jPanel11);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("PRECIO");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel26.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("CODIGO");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("NOMBRE");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel28.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("CANTIDAD");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtPrecioInventario.setBackground(new java.awt.Color(153, 255, 204));
        txtPrecioInventario.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.add(txtPrecioInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, -1));

        txtCodigoInventario.setBackground(new java.awt.Color(153, 255, 204));
        txtCodigoInventario.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.add(txtCodigoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        txtNombreInventario.setBackground(new java.awt.Color(153, 255, 204));
        txtNombreInventario.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.add(txtNombreInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        txtStockInventario.setBackground(new java.awt.Color(153, 255, 204));
        txtStockInventario.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.add(txtStockInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, -1));

        tablaInventario.setBackground(new java.awt.Color(255, 255, 255));
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "CANTIDAD", "PRECIO"
            }
        ));
        tablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaInventario);
        if (tablaInventario.getColumnModel().getColumnCount() > 0) {
            tablaInventario.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaInventario.getColumnModel().getColumn(1).setPreferredWidth(40);
            tablaInventario.getColumnModel().getColumn(2).setPreferredWidth(20);
            tablaInventario.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 400, 200));

        btnNuevoInventario.setBackground(new java.awt.Color(178, 255, 216));
        btnNuevoInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NUEVO.png"))); // NOI18N
        btnNuevoInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoInventarioActionPerformed(evt);
            }
        });
        jPanel10.add(btnNuevoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 50, 50));

        btnGuardarProducto.setBackground(new java.awt.Color(178, 255, 216));
        btnGuardarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AGREGAR.png"))); // NOI18N
        btnGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoActionPerformed(evt);
            }
        });
        jPanel10.add(btnGuardarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 50));

        btnEliminarProducto.setBackground(new java.awt.Color(178, 255, 216));
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ELIMINAR.png"))); // NOI18N
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel10.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 50, 50));

        btnActualizar.setBackground(new java.awt.Color(178, 255, 216));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ACTUALIZAR.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel10.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 50, 50));

        tab3.addTab("tab4", jPanel10);

        jPanel1.add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 550, 370));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SISTEMA DE VENTAS DROGUERIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        tab3.setSelectedIndex(0);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        tab3.setSelectedIndex(2);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        tab3.setSelectedIndex(3);
        actualizarTablaInventario();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        tab3.setSelectedIndex(1);
        actualizarTabla();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtTelefonoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoVentaActionPerformed

    private void txtNombreVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreVentaActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
          if (!validarCamposCliente()) return;

           int id = Integer.parseInt(txtIdCliente.getText().trim());
            String nombre = txtNombreCliente.getText().trim();
            String telefono = txtTelefonoCliente.getText().trim();

        boolean agregado = cl.agregarCliente(id, nombre, telefono);

        if (agregado) {
        JOptionPane.showMessageDialog(this, "Cliente agregado correctamente");
        actualizarTabla();
            } else {
        JOptionPane.showMessageDialog(this, "Error al agregar cliente. Ya existe un cliente con ese ID");
        }


        
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        if (!validarCamposCliente()) return;
        int id = Integer.parseInt(txtIdCliente.getText());
        
        boolean eliminado = cl.eliminarCliente(id);
        
        if(eliminado){
            JOptionPane.showMessageDialog(null, "Cliente eliminado correctamente");
            actualizarTabla();
        }else{
            JOptionPane.showMessageDialog(null, "Cliente no encontrado");
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        int id = Integer.parseInt(txtIdCliente.getText());
        String nuevoNombre = txtNombreCliente.getText();
        String nuevoTelefono = txtTelefonoCliente.getText();
        
        boolean actualizado = cl.actualizarCliente(id,nuevoNombre,nuevoTelefono);
        
        if(actualizado){
            JOptionPane.showMessageDialog(null,"Cliente actualizado con exito");
        }else{
            JOptionPane.showMessageDialog(null, "error: cliente no encontrado");
        }
        actualizarTabla();
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        txtIdCliente.setText("");
        txtNombreCliente.setText("");
        txtTelefonoCliente.setText("");
        actualizarTabla();
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        int fila =tablaCliente.rowAtPoint(evt.getPoint());
        txtIdCliente.setText(tablaCliente.getValueAt(fila, 0).toString());
        txtNombreCliente.setText(tablaCliente.getValueAt(fila, 1).toString());
        txtTelefonoCliente.setText(tablaCliente.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void txtCodigoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoVentaActionPerformed

    private void txtCodigoVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoVentaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        if(!"".equals(txtCodigoVenta.getText())){
            String cod = txtCodigoVenta.getText();
            Inventario.Producto pro = proD.buscarPorCodigo(cod);
            if(pro != null){
                txtDescripcionVenta.setText(pro.getNombre());
                txtPrecioVenta.setText(String.valueOf(pro.getPrecio()));
                txtStockVenta.setText(String.valueOf(pro.getStock()));
                txtCantidadVenta.setText("1"); 
            } else {
                JOptionPane.showMessageDialog(null, "Producto no encontrado");
                txtDescripcionVenta.setText("");
                txtPrecioVenta.setText("");
                txtStockVenta.setText("");
                txtCodigoVenta.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el Código");
        }
    }
    }//GEN-LAST:event_txtCodigoVentaKeyPressed

    private void txtCantidadVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadVentaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        String codigo = txtCodigoVenta.getText();
        String nombre = txtDescripcionVenta.getText();
        int stock = Integer.parseInt(txtStockVenta.getText());
        int cantidad;
        double precio;

        try {
            cantidad = Integer.parseInt(txtCantidadVenta.getText());
            precio = Double.parseDouble(txtPrecioVenta.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Cantidad o precio inválido");
            return;
        }
        if(stock >= cantidad){
        double total = cantidad * precio;
        for(int i= 0; i < modeloTablaVenta.getRowCount();i++){
            if(tableVenta.getValueAt(i,1).equals(txtDescripcionVenta.getText())){
                JOptionPane.showMessageDialog(null,"El producto ya fue registrado");
                return;
            }
        }

        // Agrega a la tabla
        modeloTablaVenta.addRow(new Object[]{
            codigo,
            nombre,
            cantidad,
            precio,
            total
        });
        
        // Limpia los campos
        txtCodigoVenta.setText("");
        txtDescripcionVenta.setText("");
        txtCantidadVenta.setText("");
        txtPrecioVenta.setText("");
        txtStockVenta.setText("");
        txtCodigoVenta.requestFocus();
        totalPagar();
        }else{
            JOptionPane.showMessageDialog(null,"Stock no disponible");
        }
    }

    }//GEN-LAST:event_txtCantidadVentaKeyPressed

    private void txtCantidadVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadVentaActionPerformed

    private void btnEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVentaActionPerformed
        modeloTablaVenta = (DefaultTableModel) tableVenta.getModel();
        modeloTablaVenta.removeRow(tableVenta.getSelectedRow());
        totalPagar();
        txtCodigoVenta.requestFocus();
    }//GEN-LAST:event_btnEliminarVentaActionPerformed

    private void txtIdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVentaActionPerformed
        if (!"".equals(txtIdVenta.getText())) {
        try {
            int id = Integer.parseInt(txtIdVenta.getText());
            cliente = cl.buscarPorId(id);

            if (cliente != null) {
                txtNombreVenta.setText(cliente.getNombre());
                txtTelefonoVenta.setText(cliente.getTelefono());
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no existe");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID inválido");
        }
    }
    }//GEN-LAST:event_txtIdVentaActionPerformed

private void inicializarTablaHistorial() {
        DefaultTableModel modeloHistorialVentas;
        modeloHistorialVentas = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
    
    modeloHistorialVentas.addColumn("ID");
    modeloHistorialVentas.addColumn("Fecha");
    modeloHistorialVentas.addColumn("ID Cliente");
    modeloHistorialVentas.addColumn("Productos");
    modeloHistorialVentas.addColumn("Total");
    
    tablaVentas.setModel(modeloHistorialVentas);
}

private void agregarVentaAlHistorial(Ventas.Venta venta) {
    String productosTexto = String.join(", ", venta.getProductos());
    
        modeloHistorialVentas.addRow(new Object[] {
        venta.getId(),
        venta.getFecha(),
        venta.getIdCliente(),
        productosTexto,
        venta.getTotal()
    });
}

    @SuppressWarnings("empty-statement")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    String fecha = obtenerFechaActual(); 
    int idCliente = obtenerIdClienteSeleccionado(); 
    List<String> productos = obtenerListaDeProductos(); 
    double total = calcularTotalVenta(); 

    int idVenta = ventas.agregarVenta(fecha, idCliente, productos, total);

    if (idVenta != -1) {
        Ventas.Venta ventaAgregada = ventas.buscarPorId(idVenta);
        agregarVentaAlHistorial(ventaAgregada);
        JOptionPane.showMessageDialog(null, "Venta guardada e impresa con éxito.");
    } else {
        JOptionPane.showMessageDialog(null, "Error al guardar la venta.");
    
};
    txtIdVenta.setText("");
    txtNombreVenta.setText("");
    txtTelefonoVenta.setText("");
    DefaultTableModel model = (DefaultTableModel) tableVenta.getModel();
    model.setRowCount(0);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
        if (!validarCamposCliente()) return;

           String codigo = txtCodigoInventario.getText().trim();
            String nombre = txtNombreInventario.getText().trim();
            int stock = Integer.parseInt(txtStockInventario.getText().trim());
            double precio = Integer.parseInt(txtPrecioInventario.getText().trim());

        boolean agregado = proD.agregarProducto(codigo, nombre, stock, precio);

        if (agregado) {
        JOptionPane.showMessageDialog(this, "Cliente agregado correctamente");
        actualizarTabla();
            } else {
        JOptionPane.showMessageDialog(this, "Error al agregar cliente. Ya existe un cliente con ese ID");
        }
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
       if (!validarCamposCliente()) return;
        String codigo = txtCodigoInventario.getText();
        
        boolean eliminado = proD.eliminarProducto(codigo);
        
        if(eliminado){
            JOptionPane.showMessageDialog(null, "Cliente eliminado correctamente");
            actualizarTabla();
        }else{
            JOptionPane.showMessageDialog(null, "Cliente no encontrado");
        }   
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String codigo = txtCodigoInventario.getText();
        String nuevoNombre = txtNombreInventario.getText();
        Integer nuevoStock = Integer.valueOf(txtStockInventario.getText());
        Double nuevoPrecio = Double.valueOf(txtPrecioInventario.getText());
        
        boolean actualizado = proD.actualizarProducto(codigo,nuevoNombre,nuevoStock,nuevoPrecio);
        
        if(actualizado){
            JOptionPane.showMessageDialog(null,"Cliente actualizado con exito");
        }else{
            JOptionPane.showMessageDialog(null, "error: cliente no encontrado");
        }
        actualizarTablaInventario();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoInventarioActionPerformed
        txtCodigoInventario.setText("");
        txtNombreInventario.setText("");
        txtStockInventario.setText("");
        txtPrecioInventario.setText("");
        actualizarTablaInventario();
    }//GEN-LAST:event_btnNuevoInventarioActionPerformed

    private void tablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInventarioMouseClicked
         int fila =tablaInventario.rowAtPoint(evt.getPoint());
        txtCodigoInventario.setText(tablaInventario.getValueAt(fila, 0).toString());
        txtNombreInventario.setText(tablaInventario.getValueAt(fila, 1).toString());
        txtStockInventario.setText(tablaInventario.getValueAt(fila, 2).toString());
        txtPrecioInventario.setText(tablaInventario.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tablaInventarioMouseClicked

    
    private int obtenerIdClienteSeleccionado() {
    if (cliente != null) {
        return cliente.getId(); 
    } else {
        JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún cliente.");
        return -1;
    }
}

    
    private List<String> obtenerListaDeProductos() {
    List<String> productos = new ArrayList<>();
    DefaultTableModel modelo = (DefaultTableModel) tableVenta.getModel();

    for (int i = 0; i < modelo.getRowCount(); i++) {
        String nombreProducto = modelo.getValueAt(i, 1).toString(); 
        productos.add(nombreProducto);
    }

    return productos;
}

    private double calcularTotalVenta() {
    return totalPagar;
}

    
    
    private String obtenerFechaActual() {
    LocalDate fechaActual = LocalDate.now();
    return fechaActual.toString(); // formato YYYY-MM-DD
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }
    private void actualizarTablaInventario() {
    DefaultTableModel model = (DefaultTableModel) tablaInventario.getModel();
    model.setRowCount(0); // Limpiar la tabla

    for (Inventario.Producto c : proD.obtenerTodos()) {
        model.addRow(new Object[]{c.getCodigo(), c.getNombre(), c.getStock(), c.getPrecio()});
    }
}
     private void actualizarTabla() {
    DefaultTableModel model = (DefaultTableModel) tablaCliente.getModel();
    model.setRowCount(0); // Limpiar la tabla

    for (Clientes.Cliente c : cl.obtenerTodos()) {
        model.addRow(new Object[]{c.getId(), c.getNombre(), c.getTelefono()});
    }
}
    
    private boolean validarCamposCliente() {
    String idTexto = txtIdCliente.getText().trim();
    String nombre = txtNombreCliente.getText().trim();
    String telefono = txtTelefonoCliente.getText().trim();

    if (idTexto.isEmpty() || nombre.isEmpty() || telefono.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
        return false;
    }

    try {
        Integer.parseInt(idTexto);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un número válido");
        return false;
    }

    return true;



}
DefaultTableModel modeloTablaVenta;

private void inicializarTabla() {
    modeloTablaVenta = new DefaultTableModel();
    
    modeloTablaVenta.addColumn("Código");
    modeloTablaVenta.addColumn("Nombre");
    modeloTablaVenta.addColumn("Cantidad");
    modeloTablaVenta.addColumn("Precio");
    modeloTablaVenta.addColumn("Total");
    tableVenta.setModel(modeloTablaVenta);
    
    tableVenta.setModel(modeloTablaVenta);
}


private void totalPagar(){
    totalPagar = 0.0;
    int numFila = tableVenta.getRowCount();
    for(int i = 0; i< numFila; i++){
        double cal = Double.parseDouble(String.valueOf(tableVenta.getModel().getValueAt(i, 4)));
        totalPagar = totalPagar + cal;
    }
    LabelTotal.setText(String.format("%.2f", totalPagar));
}
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnEliminarVenta;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoInventario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTabbedPane tab3;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTable tableVenta;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtCodigoInventario;
    private javax.swing.JTextField txtCodigoVenta;
    private javax.swing.JTextField txtDescripcionVenta;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreInventario;
    private javax.swing.JTextField txtNombreVenta;
    private javax.swing.JTextField txtPrecioInventario;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtStockInventario;
    private javax.swing.JTextField txtStockVenta;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTelefonoVenta;
    // End of variables declaration//GEN-END:variables
}
